# Waypoint follower configuration
nlgl_radius:    4.0 # m
wp_tolerance:   2.0 # m
default_speed:  2.0 # m/s

# Station keeping configuration
station_tolerance_pos_: 0.5  # m
station_tolerance_ang_: 0.35 # rad (0.35 is 20deg)